<a href="https://colab.research.google.com/github/Sank3t-Pand3y/MyPractiseML/blob/main/optuna_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.6.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.2)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.44)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.6.0-py3-none-any.whl (404 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 5.3 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.6.0

In [2]:
import optuna
from sklearn.datasets import load_diabetes
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
# Load the Pima Indian Diabetes from sklearn
# Note: Scikit-learn's builti-in 'load_diabetes' is a regression datasets.
# We will load the actual diabetes dataset from an external source
import pandas as pd

In [4]:
# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

In [5]:
# load the dataset
df = pd.read_csv(url, names = columns)

df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [6]:
import numpy as np

In [11]:
# Replace zero values with NaN in columns where zero is not a valid value
# That means :- We are Replacing 0 (zero) with NaN

cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)


# Impute the missing values with the mean of the respective column
# That means :- We are Replacing NaN with the mean of each particular column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [12]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=42)


# Optional : Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training data shape: {X_train.shape}')
print(f'Testing data shape: {X_test.shape}')

Training data shape: (537, 8)
Testing data shape: (231, 8)

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
     # n_estimators means number of the decision tree
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [16]:
# Create a study object and optimize the objective function
# direction='maximize' that is maximized cause we need the Maximum Value

study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-11-23 07:06:44,000] A new study created in memory with name: no-name-4e57c9fb-5e80-4013-b11f-33679317024b
[I 2025-11-23 07:06:46,348] Trial 0 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 183, 'max_depth': 11}. Best is trial 0 with value: 0.7672253258845437.
[I 2025-11-23 07:06:49,145] Trial 1 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 1 with value: 0.7728119180633147.
[I 2025-11-23 07:06:52,465] Trial 2 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 198, 'max_depth': 19}. Best is trial 2 with value: 0.7746741154562384.
[I 2025-11-23 07:06:53,698] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 60, 'max_depth': 12}. Best is trial 2 with value: 0.7746741154562384.
[I 2025-11-23 07:06:55,197] Trial 4 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 114, 'max_depth': 5}. Best is trial 2 with value: 0.7746741154562384.
[I 2025-11-23 07:06:55,525] Trial 5 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 2 with value: 0.7746741154562384.
[I 2025-11-23 07:06:56,148] Trial 6 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 115, 'max_depth': 4}. Best is trial 2 with value: 0.7746741154562384.
[I 2025-11-23 07:06:56,597] Trial 7 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 68, 'max_depth': 12}. Best is trial 2 with value: 0.7746741154562384.
[I 2025-11-23 07:06:56,995] Trial 8 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 64, 'max_depth': 15}. Best is trial 2 with value: 0.7746741154562384.
[I 2025-11-23 07:06:57,748] Trial 9 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 131, 'max_depth': 5}. Best is trial 2 with value: 0.7746741154562384.
[I 2025-11-23 07:06:58,718] Trial 10 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 154, 'max_depth': 15}. Best is trial 2 with value: 0.7746741154562384.
[I 2025-11-23 07:06:59,931] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 193, 'max_depth': 20}. Best is trial 2 with value: 0.7746741154562384.
[I 2025-11-23 07:07:01,031] Trial 12 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 171, 'max_depth': 17}. Best is trial 12 with value: 0.7765363128491619.
[I 2025-11-23 07:07:02,087] Trial 13 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 165, 'max_depth': 17}. Best is trial 12 with value: 0.7765363128491619.
[I 2025-11-23 07:07:03,137] Trial 14 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 169, 'max_depth': 17}. Best is trial 12 with value: 0.7765363128491619.
[I 2025-11-23 07:07:03,997] Trial 15 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 138, 'max_depth': 9}. Best is trial 12 with value: 0.7765363128491619.
[I 2025-11-23 07:07:05,585] Trial 16 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 177, 'max_depth': 16}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:07,001] Trial 17 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 148, 'max_depth': 15}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:07,558] Trial 18 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 88, 'max_depth': 17}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:08,636] Trial 19 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 176, 'max_depth': 9}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:09,596] Trial 20 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 156, 'max_depth': 14}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:10,763] Trial 21 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 186, 'max_depth': 18}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:11,980] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 199, 'max_depth': 18}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:13,058] Trial 23 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 175, 'max_depth': 18}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:14,210] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 184, 'max_depth': 14}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:15,251] Trial 25 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 164, 'max_depth': 19}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:16,441] Trial 26 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 189, 'max_depth': 16}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:17,569] Trial 27 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 144, 'max_depth': 16}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:18,730] Trial 28 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 122, 'max_depth': 13}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:20,173] Trial 29 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 181, 'max_depth': 16}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:21,312] Trial 30 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 186, 'max_depth': 10}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:22,388] Trial 31 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 176, 'max_depth': 16}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:23,380] Trial 32 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 160, 'max_depth': 16}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:24,556] Trial 33 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 187, 'max_depth': 14}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:25,630] Trial 34 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 173, 'max_depth': 13}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:26,827] Trial 35 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 194, 'max_depth': 11}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:27,439] Trial 36 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 99, 'max_depth': 19}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:28,688] Trial 37 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 13}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:29,854] Trial 38 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 179, 'max_depth': 7}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:31,262] Trial 39 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 150, 'max_depth': 16}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:32,671] Trial 40 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 168, 'max_depth': 17}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:33,872] Trial 41 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 194, 'max_depth': 19}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:35,116] Trial 42 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 192, 'max_depth': 20}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:36,264] Trial 43 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 181, 'max_depth': 18}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:37,342] Trial 44 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 160, 'max_depth': 15}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:38,537] Trial 45 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 188, 'max_depth': 17}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:39,802] Trial 46 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 200, 'max_depth': 19}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:40,870] Trial 47 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 172, 'max_depth': 19}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:41,963] Trial 48 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 200, 'max_depth': 3}. Best is trial 16 with value: 0.7783985102420857.
[I 2025-11-23 07:07:43,560] Trial 49 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 180, 'max_depth': 20}. Best is trial 16 with value: 0.7783985102420857.

In [17]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7783985102420857
Best hyperparameters: {'n_estimators': 177, 'max_depth': 16}

# A Complete New MODEL with Best Result from Trials of Hyperparamters

In [18]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

# There are also other Samplers in Optuna

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [22]:
# We use RandomSampler OPTUNA

study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-11-23 07:18:43,564] A new study created in memory with name: no-name-c11d194e-dae5-41c3-91ef-67805059f204
[I 2025-11-23 07:18:44,643] Trial 0 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 60, 'max_depth': 8}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:18:46,571] Trial 1 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 138, 'max_depth': 16}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:18:48,458] Trial 2 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 190, 'max_depth': 8}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:18:49,604] Trial 3 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 125, 'max_depth': 3}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:18:50,336] Trial 4 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 69, 'max_depth': 15}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:18:51,117] Trial 5 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 52, 'max_depth': 10}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:18:52,003] Trial 6 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 111, 'max_depth': 12}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:18:53,147] Trial 7 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 184, 'max_depth': 17}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:18:54,262] Trial 8 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 180, 'max_depth': 18}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:18:55,284] Trial 9 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 188, 'max_depth': 3}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:18:56,016] Trial 10 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 120, 'max_depth': 9}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:18:57,635] Trial 11 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 175, 'max_depth': 12}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:18:58,302] Trial 12 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 65, 'max_depth': 14}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:18:59,748] Trial 13 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 193, 'max_depth': 17}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:19:00,322] Trial 14 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 87, 'max_depth': 20}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:19:00,781] Trial 15 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 71, 'max_depth': 12}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:19:01,856] Trial 16 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 181, 'max_depth': 5}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:19:02,203] Trial 17 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 51, 'max_depth': 18}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:19:03,174] Trial 18 finished with value: 0.756052141527002 and parameters: {'n_estimators': 172, 'max_depth': 3}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:19:04,090] Trial 19 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 139, 'max_depth': 19}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:19:05,138] Trial 20 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 184, 'max_depth': 4}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:19:05,686] Trial 21 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 89, 'max_depth': 6}. Best is trial 0 with value: 0.7765363128491621.
[I 2025-11-23 07:19:06,192] Trial 22 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 80, 'max_depth': 12}. Best is trial 22 with value: 0.7783985102420856.
[I 2025-11-23 07:19:07,082] Trial 23 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 158, 'max_depth': 3}. Best is trial 22 with value: 0.7783985102420856.
[I 2025-11-23 07:19:08,105] Trial 24 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 164, 'max_depth': 6}. Best is trial 22 with value: 0.7783985102420856.
[I 2025-11-23 07:19:08,751] Trial 25 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 107, 'max_depth': 5}. Best is trial 22 with value: 0.7783985102420856.
[I 2025-11-23 07:19:10,295] Trial 26 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 159, 'max_depth': 17}. Best is trial 22 with value: 0.7783985102420856.
[I 2025-11-23 07:19:10,943] Trial 27 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 64, 'max_depth': 15}. Best is trial 22 with value: 0.7783985102420856.
[I 2025-11-23 07:19:12,332] Trial 28 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 193, 'max_depth': 8}. Best is trial 22 with value: 0.7783985102420856.
[I 2025-11-23 07:19:13,175] Trial 29 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 5}. Best is trial 22 with value: 0.7783985102420856.
[I 2025-11-23 07:19:13,909] Trial 30 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 118, 'max_depth': 7}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:14,737] Trial 31 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 143, 'max_depth': 5}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:15,460] Trial 32 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 114, 'max_depth': 8}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:15,778] Trial 33 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 50, 'max_depth': 7}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:16,697] Trial 34 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 166, 'max_depth': 3}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:17,695] Trial 35 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 14}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:18,568] Trial 36 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 136, 'max_depth': 14}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:19,486] Trial 37 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 149, 'max_depth': 7}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:19,849] Trial 38 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 57, 'max_depth': 11}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:20,681] Trial 39 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 134, 'max_depth': 9}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:21,220] Trial 40 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 98, 'max_depth': 3}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:22,240] Trial 41 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 122, 'max_depth': 7}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:24,009] Trial 42 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 193, 'max_depth': 6}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:24,534] Trial 43 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 75, 'max_depth': 20}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:25,304] Trial 44 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 140, 'max_depth': 4}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:26,375] Trial 45 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 174, 'max_depth': 12}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:27,353] Trial 46 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 162, 'max_depth': 8}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:28,330] Trial 47 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 155, 'max_depth': 20}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:29,447] Trial 48 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 185, 'max_depth': 11}. Best is trial 30 with value: 0.7821229050279329.
[I 2025-11-23 07:19:29,856] Trial 49 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 63, 'max_depth': 13}. Best is trial 30 with value: 0.7821229050279329.

In [23]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279329
Best hyperparameters: {'n_estimators': 118, 'max_depth': 7}

In [25]:
# A Complete New MODEL with Best Result from Trials of Hyperparamters


from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

# Another Type of Sampler is Grid Search.

# Here, in Grid Search, We Define the search_space explicity i.e Outside of Objective Function.

In [26]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [27]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2025-11-23 07:23:44,726] A new study created in memory with name: no-name-34bb7c17-3416-46c7-9451-47d63126b0c6
[I 2025-11-23 07:23:46,610] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-11-23 07:23:48,604] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-11-23 07:23:49,129] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-23 07:23:50,190] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-23 07:23:51,233] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-23 07:23:51,765] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-23 07:23:52,658] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-23 07:23:53,571] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-23 07:23:54,491] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-23 07:23:55,715] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-23 07:23:56,956] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-23 07:23:58,487] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-23 07:24:00,284] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-11-23 07:24:00,599] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-11-23 07:24:01,224] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-11-23 07:24:01,556] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [28]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [29]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

# OPTUNA Visualizations

In [30]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [32]:
# 1. Optimization History
plot_optimization_history(study).show()

# Objective Values = Accuracy Value

In [33]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()


# This Plot helps you to understand between Accuracy, max_depth and n_estimators

In [34]:
# 3. Slice Plot
# In Slice Plot, We indivisually plot each hyperparameters with Objective Value i.e Accuracy
plot_slice(study).show()

In [35]:
# 4. Contour Plot
plot_contour(study).show()

In [37]:
# 5. Hyperparameter Importance
# This Graph Shows which hyperparameter is the most important. Currently, it is between max_depth and n_estimators
plot_param_importances(study).show()

# The Best Feature of the OPTUNA is that We can find the best Algorithm for the Dataset with the best Hyperparameters.

# That Means We can Optimize the Multiple ML models

In [38]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [39]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [40]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2025-11-23 07:54:20,728] A new study created in memory with name: no-name-a0a428cf-77d5-456d-9b95-cdbf072fd55c
[I 2025-11-23 07:54:20,797] Trial 0 finished with value: 0.756052141527002 and parameters: {'classifier': 'SVM', 'C': 10.600508182878743, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 0 with value: 0.756052141527002.
[I 2025-11-23 07:54:26,903] Trial 1 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 245, 'learning_rate': 0.01778683339377578, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 0 with value: 0.756052141527002.
[I 2025-11-23 07:54:30,635] Trial 2 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 126, 'learning_rate': 0.033689026943473636, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.756052141527002.
[I 2025-11-23 07:54:30,698] Trial 3 finished with value: 0.707635009310987 and parameters: {'classifier': 'SVM', 'C': 29.711705217020242, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 0 with value: 0.756052141527002.
[I 2025-11-23 07:54:31,492] Trial 4 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 165, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 4 with value: 0.7728119180633147.
[I 2025-11-23 07:54:32,897] Trial 5 finished with value: 0.7560521415270017 and parameters: {'classifier': 'RandomForest', 'n_estimators': 257, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 4 with value: 0.7728119180633147.
[I 2025-11-23 07:54:34,994] Trial 6 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 287, 'learning_rate': 0.15339206443403747, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 7}. Best is trial 4 with value: 0.7728119180633147.
[I 2025-11-23 07:54:38,670] Trial 7 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 276, 'learning_rate': 0.20854867436316296, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 4 with value: 0.7728119180633147.
[I 2025-11-23 07:54:38,705] Trial 8 finished with value: 0.7486033519553073 and parameters: {'classifier': 'SVM', 'C': 0.14839019893506236, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 4 with value: 0.7728119180633147.
[I 2025-11-23 07:54:38,737] Trial 9 finished with value: 0.6852886405959032 and parameters: {'classifier': 'SVM', 'C': 25.243139455231468, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 4 with value: 0.7728119180633147.
[I 2025-11-23 07:54:38,970] Trial 10 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 50, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 4 with value: 0.7728119180633147.
[I 2025-11-23 07:54:39,761] Trial 11 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 160, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 11 with value: 0.7765363128491621.
[I 2025-11-23 07:54:40,609] Trial 12 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 172, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 11 with value: 0.7765363128491621.
[I 2025-11-23 07:54:41,517] Trial 13 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 182, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 11 with value: 0.7765363128491621.
[I 2025-11-23 07:54:42,411] Trial 14 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 181, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 11 with value: 0.7765363128491621.
[I 2025-11-23 07:54:43,074] Trial 15 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 127, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 11 with value: 0.7765363128491621.
[I 2025-11-23 07:54:44,317] Trial 16 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 216, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 11 with value: 0.7765363128491621.
[I 2025-11-23 07:54:44,944] Trial 17 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 123, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 11 with value: 0.7765363128491621.
[I 2025-11-23 07:54:45,441] Trial 18 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 89, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 11 with value: 0.7765363128491621.
[I 2025-11-23 07:54:46,653] Trial 19 finished with value: 0.7541899441340781 and parameters: {'classifier': 'RandomForest', 'n_estimators': 216, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 11 with value: 0.7765363128491621.
[I 2025-11-23 07:54:47,422] Trial 20 finished with value: 0.7783985102420857 and parameters: {'classifier': 'RandomForest', 'n_estimators': 152, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 20 with value: 0.7783985102420857.
[I 2025-11-23 07:54:48,196] Trial 21 finished with value: 0.7783985102420857 and parameters: {'classifier': 'RandomForest', 'n_estimators': 158, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 20 with value: 0.7783985102420857.
[I 2025-11-23 07:54:49,185] Trial 22 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 147, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 20 with value: 0.7783985102420857.
[I 2025-11-23 07:54:49,912] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'RandomForest', 'n_estimators': 95, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:50,723] Trial 24 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 98, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:51,260] Trial 25 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 73, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:52,509] Trial 26 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 208, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:53,080] Trial 27 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 115, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,118] Trial 28 finished with value: 0.7392923649906891 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 144, 'learning_rate': 0.01049882406650822, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,157] Trial 29 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5358308690429641, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,190] Trial 30 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.502508815622971, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,228] Trial 31 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5228711462253977, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,263] Trial 32 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5072149799005025, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,301] Trial 33 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.3293999069062024, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,335] Trial 34 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.3551656311553432, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,383] Trial 35 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.1017693989209936, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,440] Trial 36 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.0279163118098813, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,487] Trial 37 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.331890806846589, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,539] Trial 38 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.327312481932865, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,576] Trial 39 finished with value: 0.7337057728119181 and parameters: {'classifier': 'SVM', 'C': 2.8487712853380818, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,614] Trial 40 finished with value: 0.7039106145251397 and parameters: {'classifier': 'SVM', 'C': 3.513701767053692, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,667] Trial 41 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 5.305730453999605, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,710] Trial 42 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.726331953033762, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,767] Trial 43 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.3951796978481905, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:55,808] Trial 44 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.4851719630778635, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:57,088] Trial 45 finished with value: 0.7243947858472999 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 53, 'learning_rate': 0.06817048914739213, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 1}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:57,403] Trial 46 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 95.80237560400704, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:57,477] Trial 47 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 9.833302638457706, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:57,530] Trial 48 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.3834459573217295, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:59,062] Trial 49 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 73, 'learning_rate': 0.07565102271341169, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:59,105] Trial 50 finished with value: 0.7486033519553073 and parameters: {'classifier': 'SVM', 'C': 0.9955916672691322, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:59,157] Trial 51 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.722203997370838, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:59,224] Trial 52 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 7.110831664664064, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:59,278] Trial 53 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.4663020618362728, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:59,334] Trial 54 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 5.0568184616178025, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:59,382] Trial 55 finished with value: 0.750465549348231 and parameters: {'classifier': 'SVM', 'C': 16.49321082001902, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:54:59,419] Trial 56 finished with value: 0.7392923649906891 and parameters: {'classifier': 'SVM', 'C': 2.174473617857429, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:55:01,404] Trial 57 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 107, 'learning_rate': 0.29732687098820093, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 23 with value: 0.7858472998137801.
[I 2025-11-23 07:55:01,459] Trial 58 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.8767365566189502, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 58 with value: 0.7858472998137803.
[I 2025-11-23 07:55:01,524] Trial 59 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.9543070482979658, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 58 with value: 0.7858472998137803.
[I 2025-11-23 07:55:01,653] Trial 60 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.078195592374657, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 58 with value: 0.7858472998137803.
[I 2025-11-23 07:55:01,729] Trial 61 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.9829464353275377, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 58 with value: 0.7858472998137803.
[I 2025-11-23 07:55:01,786] Trial 62 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.9470560045885397, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 58 with value: 0.7858472998137803.
[I 2025-11-23 07:55:01,853] Trial 63 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.3881507466184844, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 58 with value: 0.7858472998137803.
[I 2025-11-23 07:55:01,913] Trial 64 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 1.6894084507112537, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 58 with value: 0.7858472998137803.
[I 2025-11-23 07:55:01,986] Trial 65 finished with value: 0.7541899441340782 and parameters: {'classifier': 'SVM', 'C': 6.97371148472336, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 58 with value: 0.7858472998137803.
[I 2025-11-23 07:55:02,111] Trial 66 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 9.666438584602336, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 58 with value: 0.7858472998137803.
[I 2025-11-23 07:55:05,092] Trial 67 finished with value: 0.74487895716946 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 199, 'learning_rate': 0.0320013373308688, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 10}. Best is trial 58 with value: 0.7858472998137803.
[I 2025-11-23 07:55:05,134] Trial 68 finished with value: 0.7243947858472998 and parameters: {'classifier': 'SVM', 'C': 3.0115588817225594, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 58 with value: 0.7858472998137803.
[I 2025-11-23 07:55:05,164] Trial 69 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12252172302055128, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 69 with value: 0.7895716945996275.
[I 2025-11-23 07:55:06,453] Trial 70 finished with value: 0.7579143389199255 and parameters: {'classifier': 'RandomForest', 'n_estimators': 228, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 69 with value: 0.7895716945996275.
[I 2025-11-23 07:55:06,486] Trial 71 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10138929449725012, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 69 with value: 0.7895716945996275.
[I 2025-11-23 07:55:06,519] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14182602592646285, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 69 with value: 0.7895716945996275.
[I 2025-11-23 07:55:06,551] Trial 73 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10220923027558108, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 69 with value: 0.7895716945996275.
[I 2025-11-23 07:55:06,583] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12181425686597319, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 69 with value: 0.7895716945996275.
[I 2025-11-23 07:55:06,617] Trial 75 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10481591735022254, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 69 with value: 0.7895716945996275.
[I 2025-11-23 07:55:06,650] Trial 76 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10043258300514472, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 69 with value: 0.7895716945996275.
[I 2025-11-23 07:55:06,682] Trial 77 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10139887435933975, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 69 with value: 0.7895716945996275.
[I 2025-11-23 07:55:06,716] Trial 78 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10820259295292767, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 69 with value: 0.7895716945996275.
[I 2025-11-23 07:55:06,751] Trial 79 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2113962774984693, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 69 with value: 0.7895716945996275.

In [41]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.12252172302055128, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

In [42]:
# We can Print all the Trials that Occuried inside the DataFrame
study.trials_dataframe()

    number     value  ... params_n_estimators     state
0        0  0.756052  ...                 NaN  COMPLETE
1        1  0.750466  ...               245.0  COMPLETE
2        2  0.735568  ...               126.0  COMPLETE
3        3  0.707635  ...                 NaN  COMPLETE
4        4  0.772812  ...               165.0  COMPLETE
..     ...       ...  ...                 ...       ...
95      95  0.787709  ...                 NaN  COMPLETE
96      96  0.783985  ...                 NaN  COMPLETE
97      97  0.765363  ...               251.0  COMPLETE
98      98  0.789572  ...                 NaN  COMPLETE
99      99  0.785847  ...                 NaN  COMPLETE

[100 rows x 16 columns]

In [44]:
# Each Algorithm kati choti RUN vayo.
# i.e. 100 trails thiyo
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 69
RandomForest        21
GradientBoosting    10
Name: count, dtype: int64

In [46]:
# Each Algorithm ko Average kati cha, we can find it
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.745438
RandomForest        0.769354
SVM                 0.775754
Name: value, dtype: float64